# Generated by Django 4.2.5 on 2023-10-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturezaApp', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutri',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
