# Generated by Django 4.2.5 on 2023-10-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturezaApp', '0003_product_nutri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutri',
            field=models.IntegerField(default=100),
        ),
    ]
